name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: coursier/cache-action@v6      

      - name: Setup
        run: |
          PLATFORM="$(uname)"

          if [ $PLATFORM == "Darwin" ]; then
            echo "It's a Mac"
            brew install llvm@17 sbt
          else
            echo "It's a Linux"
            sudo apt update
            sudo apt install lsb-release wget software-properties-common
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb http://apt.llvm.org/focal/     llvm-toolchain-focal-13   main"
            sudo apt-get update 
            sudo apt-get install clang-17 lldb-17 libclang-17-dev llvm-17-dev
          fi

          cd raylib/src && make PLATFORM=PLATFORM_DESKTOP

      - name: Compile examples
        run: sbt run
